baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Coffee & Learn ☕️'
primary: true
siteGroup: 2507e5aa-62d0-4d14-8335-6e74e5041053 # Foundation
sortOrder: 1
